version: "3.3"

services:
  telegraf:
    image: telegraf:1.21
    entrypoint: "/usr/bin/telegraf"
    command: ""
    networks:
      - outside
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: telegraf-bis.conf
        target: /etc/telegraf/telegraf.conf
    deploy:
      mode: global

  influxdb:
    image: influxdb:1.3.5-alpine
    networks:
      - traefik
    ports:
      - 8086:8086
    configs:
      - source: influxdb-1.conf
        target: /etc/influxdb/influxdb.conf
    volumes:
      - influxvolume:/var/lib/influxdb
    deploy:
      replicas: 1

  grafana:
    image: grafana/grafana:4.5.2
    networks:
      - traefik
    ports:
      - 3000:3000
    volumes:
      - grafanavolume:/var/lib/grafana
    deploy:
      placement:
        preferences:
          - spread: node.labels.node
      replicas: 2
      labels:
        - traefik.http.services.grafana.loadbalancer.server.port=3000
        - traefik.http.routers.grafana.rule=Host(`grafana.ensg.duckdns.org`)
        - traefik.enable=true

volumes:
  influxvolume:
    driver: glusterfs
    driver_opts:
          replica: 2
  grafanavolume:
    driver: glusterfs
    driver_opts:
          replica: 2
configs:
  telegraf-bis.conf:
    file: ./telegraf.conf
  influxdb-1.conf:
    file: ./influxdb.conf

networks:
  outside:
    external:
      name: "host"
  traefik:
    external:
      name: "traefik"
