version: "3.3"

services:
  telegraf:
    image: telegraf:1.4.0
    networks:
      - outside
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: telegraf.conf
        target: /etc/telegraf/telegraf.conf
    deploy:
      mode: global

  influxdb:
    image: influxdb:1.3.5-alpine
    ports:
      - 8086:8086
    configs:
      - source: influxdb.conf
        target: /etc/influxdb/influxdb.conf
    volumes:
      - influxvolume:/var/lib/influxdb

  grafana:
    image: grafana/grafana:4.5.2
    networks:
      - traefik
    ports:
      - 3000:3000
    volumes:
      - grafanavolume:/var/lib/grafana
    deploy:
      labels:
        - traefik.http.services.grafana.loadbalancer.server.port=3000
        - traefik.http.routers.grafana.rule=Host(`grafana.ensg.duckdns.org`)
        - traefik.enable=true

volumes:
  influxvolume:
    driver: glusterfs
  grafanavolume:
    driver: glusterfs

configs:
  telegraf.conf:
    file: ./telegraf.conf
  influxdb.conf:
    file: ./influxdb.conf

networks:
  outside:
    external:
      name: "host"
  traefik:
    external:
      name: "traefik"