version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - --api.insecure=true 
      - --providers.docker
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      # uncomment this lines to test and debug
      #- --log.level=DEBUG
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - --certificatesresolvers.myresolver.acme.email=tsic21@ensg.eu
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      # change loaction logs
      - --log.filePath=/logs_traefik/traefik.log
      # save metrics into influxDB
      # - --metrics.influxdb=true
      # - --metrics.influxdb.address=MONITORING_influxdb:8086
      # - --metrics.influxdb.protocol=udp
      # - --metrics.influxdb.database=traefik
      # - --metrics.influxdb.username=tsi
      # - --metrics.influxdb.password=secret
      # - --metrics.influxdb.addEntryPointsLabels=true
      # - --metrics.influxdb.addServicesLabels=true
      # - --metrics.influxdb.pushInterval=10s
    ports:
      # The HTTP port
      - "81:80"
      # The Web UI (enabled by --api.insecure=true)
      - "443:443"
      - "8081:8080"
    volumes:
    # Volumes to persiste certificat uncomment if you want to dont ask them everytim use glusterFS
      - letsEncrypt:/letsencrypt
      - logs_traefik:/logs_traefik
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager
          #Add network
#     networks:
#       - MONITORING_default
# networks:
#   MONITORING_default:
#     external:
#       name: MONITORING_default
volumes:
  letsEncrypt:
    driver: glusterfs
    driver_opts:
      replica: 2
  logs_traefik:
    driver: glusterfs
    driver_opts:
      replica: 2

