version: '3'

services:
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    deploy:
      labels:
        # - traefik.http.services.whoami.loadbalancer.server.port=80
        - traefik.http.services.whoami.entrypoints=websecure
        - traefik.http.services.whoami.tls.certresolver=myresolver
    networks:
      - traefik_default
networks:
  traefik_default:
    external:
      name: traefik_default