version: '3.4'

services:
  onlyoffice:
    image: onlyoffice/documentserver:latest
    restart: always
    stdin_open: true
    tty: true
    networks:
      - traefik
      - mysql-nextcloud
    deploy:
      replicas: 0
      placement:
        preferences:
          - spread: node.labels.node
      labels:
        - traefik.http.services.onlyoffice.loadbalancer.server.port=80
        - traefik.enable=true
        - traefik.http.routers.onlyoffice.rule=Host(`nextcloud.ensg.duckdns.org`) && PathPrefix(`/onlyoffice`)
        - traefik.http.routers.onlyoffice.middlewares=onlyoffice-headers,onlyoffice-pathstrip
        - traefik.http.middlewares.onlyoffice-headers.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.middlewares.onlyoffice-headers.headers.customrequestheaders.X-Forwarded-Host=nextcloud.e>
        - traefik.http.middlewares.onlyoffice-headers.headers.customresponseheaders.X-Frame-Options=SAMEORIGIN
        - traefik.http.middlewares.onlyoffice-headers.headers.accessControlAllowOriginList=*
        - traefik.http.middlewares.onlyoffice-pathstrip.stripprefix.prefixes=/onlyoffice/
        
        
networks:
  mysql-nextcloud:
    driver: overlay
    attachable: true
  traefik:
    external: true
        
        
